# Generated by Django 3.1 on 2020-09-21 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_employer_freelancer_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='project',
            name='price_employer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='interested_freelancers',
            field=models.ManyToManyField(blank=True, related_name='interested_projects', to='djangoapp.Freelancer'),
        ),
        migrations.AlterField(
            model_name='project',
            name='producer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_produced', to='djangoapp.employer'),
        ),
        migrations.AlterField(
            model_name='project',
            name='solver',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_solved', to='djangoapp.freelancer'),
        ),
        migrations.CreateModel(
            name='Price_Suggested_By_Freelancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('freelancer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='djangoapp.freelancer')),
                ('project', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='djangoapp.project')),
            ],
        ),
    ]
