# Generated by Django 3.1 on 2020-09-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_auto_20200921_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
