# Generated by Django 2.2.5 on 2020-10-09 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_free_employer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='free_employer',
        ),
    ]
