# Generated by Django 2.2.5 on 2020-10-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0007_auto_20201017_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='expert_freelancers',
            field=models.ManyToManyField(blank=True, related_name='expert_categories', to='djangoapp.Freelancer'),
        ),
        migrations.AddField(
            model_name='employer',
            name='cup',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employer',
            name='image',
            field=models.ImageField(blank=True, upload_to='images_profile'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='cup',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='cv',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='education',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='image',
            field=models.ImageField(blank=True, upload_to='images_profile'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='project',
            name='files',
            field=models.FileField(blank=True, upload_to='files_project'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='project_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
