# Generated by Django 2.2.5 on 2020-10-25 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0008_auto_20201025_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='solver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_solved', to='djangoapp.Freelancer'),
        ),
    ]
