# Generated by Django 2.2.5 on 2020-10-29 07:48

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0009_auto_20201025_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='delivery_date',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2020, 10, 29, 11, 17, 59, 943247), verbose_name='تاریخ تحویل'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_duration',
            field=models.IntegerField(default=0),
        ),
    ]
