# Generated by Django 2.2.5 on 2020-10-29 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0010_auto_20201029_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='delivery_date',
        ),
        migrations.AddField(
            model_name='project',
            name='project_day_delivery',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='project_month_delivery',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='project_year_delivery',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 29, 12, 26, 26, 266806)),
        ),
    ]
