# Generated by Django 2.2.5 on 2020-11-06 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0011_auto_20201029_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='related_fields',
            field=models.ManyToManyField(blank=True, related_name='projects_related', to='djangoapp.Related_subject'),
        ),
        migrations.AlterField(
            model_name='project',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 14, 30, 20, 35948)),
        ),
    ]
